name: IssueToTrello

# Controls when the workflow will run
on: 
  issues:
    types: closed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      GTOKEN: ${{ secrets.G_TOKEN }}
      TOKEN: ${{ secrets.TRELLO_TOKEN }}
      KEY: ${{ secrets.TRELLO_KEY }}
      NUMBER: ${{ github.event.issue.number }}
      LIST: 60e97d69924ed0242a84897b
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: download card id
        uses: actions/upload-artifact@v2
        with:
          name: issue-$NUMBER
      - name: review trello card
        run: |
          data="dueComplete=true&idList=$LIST&token=$TOKEN&key=$KEY"
          card_id='cat id.txt'
          curl --request PUT -s -o /dev/null -d $data https://api.trello.com/1/cards/$card_id
