# This is a basic workflow to help you get started with Actions

name: IssueToTrello

# Controls when the workflow will run
on: 
  issues:
    types: opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TRELLO_TOKEN }}
      KEY: ${{ secrets.TRELLO_KEY }}
      CONTEX: ${{ toJson(github) }}
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: create trello card
        run: |
          echo $TOKEN,
          echo $GITHUB_EVENT_PATH,
          echo $CONTEXT
