# This is a basic workflow to help you get started with Actions

name: IssueToTrello

# Controls when the workflow will run
on: 
  issues:
    types: opened

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  create:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    env:
      TOKEN: ${{ secrets.TRELLO_TOKEN }}
      KEY: ${{ secrets.TRELLO_KEY }}
      TITLE: ${{ github.event.issue.title }}
      NUMBER: ${{ github.event.issue.number }}
      URL: ${{ github.event.issue.html_url }}
      LIST: 607e0b1b0fb8813ef34d468e
      DESC: ${{ github.event.issue.body}}
      LABEL: 6078af083315ab67b7d21f2c
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Runs a set of commands using the runners shell
      - name: create trello card
        run: |
          safe_name=$(echo "[$NUMBER] "$TITLE|tr ' ' '+')
          safe_desc=$(echo $DESC|tr ' ' '+')
          card="name="$safe_name"&desc=$safe_desc&due=null&idLabels=$LABEL&idList=$LIST&token=$TOKEN&key=$KEY"
          attach="url="$URL"&token=$TOKEN&key=$KEY"
          card_id=$(curl -s --data $card https://api.trello.com/1/cards | jq -r '.id')
          curl -s -o /dev/null --data $attach https://api.trello.com/1/cards/$card_id/attachments

          
